README.md

Updated the incorrect path to the example todo app in the README file to point to the correct location at examples/react/todo

docs: fix example todo app path in README

---

packages/optimistic/src/collection.ts
packages/optimistic/src/types.ts
packages/optimistic/tests/collection.test.ts
packages/react-optimistic/tests/useCollection.test.tsx

Don't wait for transaction to finish before applying synced transactions

---

packages/optimistic/src/TransactionManager.ts
packages/optimistic/src/collection.ts
packages/optimistic/src/types.ts
packages/optimistic/tests/TransactionManager.test.ts
packages/optimistic/tests/collection.test.ts
packages/react-optimistic/tests/electric.test.ts

Fix #34 
This type of behavior *is* desired but better lives in user land where we can supported infinite flavors of queuing/batching/merging/etc. See #35 for thoughts.

Remove the idea of ordered/serialized transactions

---

packages/optimistic/src/query/compiled-query.ts
packages/optimistic/src/query/index.ts
packages/optimistic/src/query/pipeline-compiler.ts
packages/optimistic/src/query/query-builder.ts
packages/optimistic/src/query/result-collection.ts
packages/optimistic/tests/query/compiler.test.ts
packages/optimistic/tests/query/conditions.test.ts
packages/optimistic/tests/query/function-integration.test.ts
packages/optimistic/tests/query/group-by.test.ts
packages/optimistic/tests/query/having.test.ts
packages/optimistic/tests/query/in-operator.test.ts
packages/optimistic/tests/query/join.test.ts
packages/optimistic/tests/query/key-by.test.ts
packages/optimistic/tests/query/like-operator.test.ts
packages/optimistic/tests/query/nested-conditions.test.ts
packages/optimistic/tests/query/order-by.test.ts
packages/optimistic/tests/query/query-builder/from.test.ts
packages/optimistic/tests/query/query-builder/group-by.test.ts
packages/optimistic/tests/query/query-builder/having.test.ts
packages/optimistic/tests/query/query-builder/join.test.ts
packages/optimistic/tests/query/query-builder/key-by.test.ts
packages/optimistic/tests/query/query-builder/order-by.test.ts
packages/optimistic/tests/query/query-builder/select-functions.test.ts
packages/optimistic/tests/query/query-builder/select.test.ts
packages/optimistic/tests/query/query-builder/where.test.ts
packages/optimistic/tests/query/query-builder/with.test.ts
packages/optimistic/tests/query/query-collection.test.ts
packages/optimistic/tests/query/table-alias.test.ts
packages/optimistic/tests/query/wildcard-select.test.ts
packages/optimistic/tests/query/with.test.ts

Working query compiler and execution for Collections:
```ts
// Start with a collection
const collection = new Collection<Person>({
// config...
})
// Build a query
const query = queryBuilder()
.from({ collection })
.where(`@age`, `>`, 30)
.keyBy(`@id`) // <- required at the moment
.select(`@id`, `@name`)
// Compile it
const compiledQuery = compileQuery(query)
// Start the query
compiledQuery.start()
// Get the "ResultCollection"
const result = compiledQuery.results
```
Outstanding things to do - probably in a followup PR:
- Make it work with un-keyed queries
- More tests! (we only have a small basic test at the moment...
- Refine what a `ResultCollection` is
- React hooks

feat: query collections

---

examples/react/todo/src/DevTools.tsx
packages/optimistic/src/collection.ts
packages/optimistic/src/types.ts
packages/optimistic/tests/collection-subscribe-changes.test.ts
packages/optimistic/tests/collection.test.ts

Do pause syncing while a mutationFn is active

---

README.md

Simplify the README usage example and re-jig the usage guide. Generally aiming to highlight the more familiar usage patterns first and defer more complex topics/patterns like sync config and generic mutations ingest until further down.
Also simplifies the mutationFn examples by keeping them specific when used with Query, rather than suggesting that generic functions are the norm.
https://github.com/TanStack/db/blob/thruflo/revise-readme/README.md

docs: simplify README usage example and update usage guide.

---

README.md
docs/index.md
examples/react/todo/src/App.tsx
packages/db-collections/src/query.ts
packages/db-collections/tests/query.test.ts

Working on the design for https://github.com/TanStack/db/issues/79 made me realize `getPrimaryKey` is a lousy function name.

Replace getPrimaryKey w/ getId

---

.changeset/bumpy-wombats-yell.md
README.md
docs/index.md
examples/react/todo/src/App.tsx
packages/db-collections/src/query.ts
packages/db-collections/tests/query.test.ts

This adds a new `refetch()` method as an alternative to `invalidate()` and updates the docs and examples to use it.

collections: add `QueryCollection.refetch()`.

---

.changeset/smooth-hairs-look.md
packages/db/src/collection.ts

if you mutated two collections in a single transaction, the optimistic state would bleed into the other collections.

fix(db): correctly filter optimistic ops by collection

---

docs/config.json
docs/framework/react/adapter.md
docs/framework/solid/adapter.md
docs/framework/svelte/adapter.md
docs/framework/vue/adapter.md
docs/installation.md
docs/overview.md
docs/quick-start.md
examples/react/todo/package.json
package.json
pnpm-lock.yaml

Creates a `docs/config.json` so that tanstack.com can load docs from this repo.
Also, changed the example's package versions from workspace to their real versions so that they can eventually run in a sandbox on the docs website. (root package.json overrides with workspace* version for local dev still)

docs: add docs config and proper example docs overrides

---

.changeset/full-steaks-wait.md
packages/db/src/query/query-builder.ts
packages/db/src/query/schema.ts
packages/db/src/query/select.ts
packages/db/tests/query/conditions.test.ts
packages/db/tests/query/query-builder/select.test.ts
packages/db/tests/query/query-collection.test.ts

this add the option for select to take a callback function for generating the final row objects. It reseves an object as the context of the row, namespaced with each input collection - essentially what a multiple input (i.e. query with joins) query would return.
```ts
useLiveQuery((query) =>
query
.from({ collection })
.select(({ collection }) => ({
displayName: `${collection.name} (Age: ${collection.age})`,
status: collection.isActive ? `Active` : `Inactive`,
ageGroup:
collection.age < 30
? `Young`
: collection.age < 40
? `Middle`
: `Senior`,
emailDomain: collection.email.split(`@`)[1],
})
)
```
Internally it is also possible to provide both the original references and new callbacks - we should leverage this undocumented until we have a new syntax replacing the original: …

feat: select callback

---

.changeset/light-hands-love.md
.gitignore
README.md
docs/overview.md
examples/react/todo/src/App.tsx
packages/db-collections/src/electric.ts
packages/db-collections/src/query.ts
packages/db-collections/tests/electric.test.ts
packages/db-collections/tests/query.test.ts
packages/db/src/collection.ts
packages/db/src/transactions.ts
packages/db/src/types.ts
packages/db/tests/collection.test.ts

Fix #132 
This change introduces a more streamlined and intuitive API for handling mutations by allowing `onInsert`, `onUpdate`, and `onDelete` handlers to be defined directly on the collection configuration.
When `collection.insert()`, `.update()`, or `.delete()` are called outside of an explicit transaction (i.e., not within `useOptimisticMutation`), the library now automatically creates a single-operation transaction and invokes the corresponding handler to persist the change.
Key changes:
-   **`@tanstack/db`**: The `Collection` class now supports `onInsert`, `onUpdate`, and `onDelete` in its configuration. Direct calls to mutation methods will throw an error if the corresponding handler is not defined.
-   **`@tanstack/db-collections`**:
-   `queryCollectionOptions` now accepts the …

Add onInsert/onUpdate/onDelete handlers to collections

---

packages/db/tests/query/query-collection.test.ts

I added a unit test to ensure ordering on a date property works. It used to be broken before (cf. https://github.com/orgs/TanStack/projects/5/views/1?pane=issue&itemId=113401831&issue=TanStack%7Cdb%7C123) because we were relying on string comparison which was broken. We've previously fixed string comparison and we're now using JS' built-in `<` comparison on Dates.

chore: Unit test for ordering by a date property

---

.changeset/solid-sloths-flash.md
packages/db-collections/src/index.ts
packages/db-collections/tests/electric.test.ts
packages/db/src/transactions.ts

`ElectricCollectionUtils` is needed to type `awaitTxId` in `useOptimisticMutation`

Export `ElectricCollectionUtils` & allow passing generic to `createTransaction` & fix some type issues in tests

---

.changeset/tiny-adults-shave.md
.github/workflows/pr.yml
docs/overview.md
examples/react/todo/src/App.tsx
packages/db-collections/package.json
packages/db-collections/src/electric.ts
packages/db-collections/src/query.ts
packages/db-collections/tests/electric.test-d.ts
packages/db-collections/tests/query.test.ts
packages/db/src/collection.ts
packages/db/src/query/compiled-query.ts
packages/db/src/types.ts
packages/db/tests/collection.test-d.ts
packages/db/tests/collection.test.ts
packages/db/tests/query/query-collection.test.ts
pnpm-lock.yaml

You now must either pass an explicit type or schema - passing both will conflict.
I also removed the broken `preloadCollection` so I didn't have to fix its types 😆 the plan is make collections lazy by default and expose a `.start()` method which returns a promise that resolves when the collection finishes loading.
Fix #116 #76

If a schema is passed, use that for the collection type

---

packages/db/src/SortedMap.ts
packages/db/src/collection.ts
packages/db/src/query/compiled-query.ts
packages/db/src/query/query-builder.ts
packages/db/src/types.ts
packages/db/tests/collection-subscribe-changes.test.ts
packages/db/tests/query/query-builder/order-by.test.ts
packages/db/tests/query/query-collection.test.ts
packages/react-db/tests/useLiveQuery.test.tsx
packages/vue-db/tests/useLiveQuery.test.ts

This PR modifies the collection's `orderBy` method to use a fractional index which is more efficient than the numeric index. I also modified the collection such that it internally keeps a sorted map of key-value pairs (`public syncedData: Map<TKey, T> | SortedMap<TKey, T>`) when the query results are ordered. I modified the `SortedMap` implementation to use binary search for finding the insert position instead of appending and re-sorting the array on each insert. For delete, we also use binary search instead of doing a linear search.

Modify `orderBy` to use a fractional index

---

packages/db-collections/src/index.ts

Currently the ElectricCollectionUtils are exported but the QueryCollectionUtils aren't.
This PR also exports the `QueryCollectionUtils` so you can use them in your collection definition for type safe `utils.refetch()` usage.

collections: export QueryCollectionUtils.

---

.changeset/gold-friends-pull.md
packages/db/src/collection.ts
packages/db/src/transactions.ts
packages/db/tests/collection-subscribe-changes.test.ts

We have experienced various issues with the change events where they could be doubled up or missed. I think this fixes it all...

fix change events

---

packages/db/src/query/builder/index.ts
packages/db/src/query/compiler/group-by.ts
packages/db/src/query/compiler/index.ts
packages/db/src/query/ir.ts
packages/db/tests/query/builder/functional-variants.test.ts
packages/db/tests/query/functional-variants.test-d.ts
packages/db/tests/query/functional-variants.test.ts

stacked on #185
In the old query builder you could call the same methods with a callback for the functional behaviour, but with the new query builder its always a callback with makes the api very hard to function as both an expression builder or functional callback. Because of that I think it's best to split these variates out as distinct functions.
For this first pass I have namespaces these under `.fn` on the query builder, but we could have then on the main object with a prefix/suffix.
```ts
const liveCollection = createLiveQueryCollection({
startSync: true,
query: (q) =>
q
.from({ user: usersCollection })
.fn.select((row) => ({
displayName: `${row.user.name} (${row.user.id})`,
salaryTier: row.user.salary > 60000 ? `senior` : `junior`,
emailDomain: row.user.email.split(`@`)[1],
})),
}) …
```

WIP functional variants of the select, where and having query builder methods

---

.changeset/khaki-cougars-give.md
.changeset/open-foxes-say.md
packages/db/src/collection.ts
packages/db/src/transactions.ts

While working on #204 I found two bugs:
1. direct insert/update/delete mutations where not settings an id on the transaction, this resulted in them being overwritten with further synchronous mutations as they had an id or `undefined` when being looked up. I have fixed that by ensuring that a transaction id will always fallback to a new uuid if not set.
@KyleAMathews you used `new Transaction()` rather than `createTransaction()` in these mutations, this means they are not added to the global list of transactions. Is this intentional or should then use `createTransaction()`? If so I will fix that here as it's a very related bug, the id was enforced in `createTransaction`, but not in the Transaction constructor.
2. transactions were sorted by `createdAt` when rebasing over the latest synced …

fix transaction sorting order and enforce them having an id

---

.changeset/khaki-cougars-give.md
.changeset/local-only-collection.md
.changeset/open-foxes-say.md
docs/overview.md
packages/db-collections/src/index.ts
packages/db-collections/src/local-only.ts
packages/db-collections/tests/local-only.test-d.ts
packages/db-collections/tests/local-only.test.ts
packages/db/src/collection.ts
packages/db/src/transactions.ts

**Stacked on #230 - merge that first!**
This just loops back on the sync interface applying all changes immediately.
~~There is a failing tests, I'm suspicious it is exposing something else going on that we need to look at.~~ *(edit: fixed in #230)*
----
A `localOnly` collection type was implemented in `@tanstack/db-collections`.
Key changes include:
*   A new file `packages/db-collections/src/local-only.ts` was created, exporting `localOnlyCollectionOptions` and related types.
*   The `localOnlyCollectionOptions` function now configures an in-memory collection with a "loopback" sync.
*   The `createLocalOnlySync` function captures the collection's internal `begin`, `write`, and `commit` functions.
*   `onInsert`, `onUpdate`, and `onDelete` handlers were introduced to …

localOnlyCollectionOptions collection for ephemeral local state

---

.changeset/slick-ghosts-shine.md
packages/db/package.json
packages/db/src/query/builder/index.ts
packages/db/src/query/compiler/index.ts
packages/db/src/query/ir.ts
packages/db/tests/query/distinct.test.ts
pnpm-lock.yaml

This PR adds support for a SQL-like `distinct` operator on queries.
It works on top of https://github.com/electric-sql/d2ts/pull/80 so we need to wait until that PR is merged and a new version of d2mini is released. Until then CI will be red.

feat: Distinct operator for queries

---

examples/react/todo/src/routes/trailbase.tsx
packages/trailbase-db-collection/src/trailbase.ts

Also avoid use of WeakRef by explicitly tying the cleanup lifetime to the livelihood of the reader.

Delay initializing periodic cleanup until sync has actually started.

---

.changeset/pink-ducks-fix.md
packages/db/src/query/compiler/joins.ts
packages/db/tests/query/join.test.ts

fixes #277
Currently the order of the references in the join `eq(left.prop, right.prop)` was required but not validated. This changes it to work either way (you can specify them in reverse) and validates and rejects other mistakes.

fix join expression order bug and add validation

---

.changeset/late-icons-fly.md
packages/db/src/indexes/btree-index.ts
packages/db/src/query/builder/index.ts
packages/db/src/query/builder/types.ts
packages/db/src/query/compiler/order-by.ts
packages/db/src/query/ir.ts
packages/db/src/utils/comparison.ts
packages/db/tests/query/builder/order-by.test.ts
packages/db/tests/query/optimizer.test.ts
packages/db/tests/query/order-by.test.ts

Fixes https://github.com/TanStack/db/issues/212 and fixes https://github.com/TanStack/db/issues/229 by adding a configuration argument to `orderBy`:
```ts
orderBy(
callback: OrderByCallback<TContext>,
options: OrderByDirection | OrderByOptions = `asc`
)
type OrderByOptions = {
direction?: OrderByDirection
nulls?: `first` | `last`
} & StringSortOpts
type StringSortOpts =
| {
stringSort?: `lexical`
}
| {
stringSort?: `locale`
locale?: string
localeOptions?: object
}
```

Configuration options for sortBy

---

.changeset/fast-poets-read.md
packages/query-db-collection/package.json
packages/query-db-collection/src/query.ts
packages/query-db-collection/tests/query.test-d.ts
pnpm-lock.yaml

Implements automatic type inference from `queryFn` return type for `query-db-collection`, following the same pattern as `electric-db-collection`.
- Added `InferQueryFnOutput<TQueryFn>` type helper to extract item types from queryFn return type
- Implemented `ResolveType` system with priority order:
1. **Explicit type** (highest priority)
2. **Schema inference** (second priority)  
3. **QueryFn return type inference** (third priority)
4. **Fallback** to `Record<string, unknown>`
- Updated `QueryCollectionConfig` interface to support new type resolution
- Added comprehensive type tests for all inference patterns
- Maintained backward compatibility with existing usage
```typescript
const collection = createCollection(
queryCollectionOptions({
queryKey: ['todos'],
queryFn: async () => {
const …
```

feat: Add type inference from queryFn return type

---

.changeset/ready-poems-fail.md
packages/react-db/src/useLiveQuery.ts
packages/react-db/tests/useLiveQuery.test.tsx

incorporates the test from #349 and fixes the issue.

ensure that react useLiveQuery returns a stable ref when there are no changes

---

.changeset/shiny-phones-stick.md
packages/db/src/collection.ts
packages/db/src/types.ts

Closes https://github.com/TanStack/db/issues/407
I wasn't sure whether it's fine to install dependency for it, or just copy paste it (but the type is a little bit bulky). As this type unfortunately has a lot of weird edge cases 😅 Lmk if you'd prefer to avoid the dependency!

fix: make item drafts mutable

---

.changeset/new-swans-heal.md
packages/db/src/query/live/collection-subscriber.ts
packages/db/tests/query/live-query-collection.test.ts
packages/db/tests/utls.ts

Fixes #438
The issue was that the subscription to the live changes could start emitting results before we had first done any join processing. The join called either `loadKeys` or `loadInitialState` depending on if there was an index it could use. These now set a flag to indicate that we now actually want to start tailing the live changes, until then they are filtered out. We still have to send an empty array of changes when there are any before then so that the query is notified of any collection status change.
Failed test run with repo before it's then fixed: https://github.com/TanStack/db/actions/runs/17233860827/job/48894002331?pr=451

fix race condition in loading joined collections into live query

---

.changeset/shaggy-worlds-kick.md
packages/db/src/query/live/collection-config-builder.ts
packages/db/src/query/live/collection-subscriber.ts
packages/db/tests/query/indexes.test.ts

This PR fixes https://github.com/TanStack/db/issues/435
The bug was caused by our optimization of `orderBy` which tries to lazily load `offset + limit` items. However, if collection doesn't have enough items to fill the results, the query pipeline kept trying to load more data from the collection. I added a unit test that reproduced this bug.
This PR fixes the problem by introducing an explicit stop condition which avoids re-running the graph if we didn't load any data (because we exhausted the collection).

Fix infinite loop in orderBy

---

.changeset/eleven-towns-carry.md
packages/electric-db-collection/src/electric.ts
packages/electric-db-collection/tests/electric.test.ts

I tried to add a test to validate that a 409 didn't reach the onError handler, but it would require very complex mocking, and time is limited...

fix handling of electric must-refetch

---

.changeset/neat-queens-smile.md
packages/db/src/collection.ts
packages/db/tests/collection-lifecycle.test.ts
packages/electric-db-collection/tests/electric.test.ts

The intention was that setting `gcTime=0` would disable it, this was not true.
I've also added tests to the electric collection to validate that it will restart the sync after being GC'd and resubscribed too.

fix disabling of gc by settings `gcTime=0`

---

docs/guides/error-handling.md

I removed the await to fix the compile error in this PR.
Also, not fixed in this PR, but FYI - the `createCollection` call above also throws a TS error.

Fix error example which doesn't compile

---

.changeset/lemon-queens-pump.md
packages/db/src/query/compiler/group-by.ts
packages/db/src/query/compiler/index.ts
packages/db/src/query/compiler/order-by.ts
packages/db/tests/query/order-by.test.ts

Fixes https://github.com/TanStack/db/issues/466 such that queries can order grouped results based on aggregates. This means we support queries like this one:
```ts
q
.from({ vehicleDocuments: vehicleDocumentCollection })
.groupBy((q) => q.vehicleDocuments.vin)
.orderBy(
(q) => max(q.vehicleDocuments.updatedAt), // couldn't do this before
"desc"
)
.select((q) => ({
vin: q.vehicleDocuments.vin,
updatedAt: max(q.vehicleDocuments.updatedAt),
}))
```

Support ordering grouped results based on aggregates

---

.changeset/deep-bushes-sell.md
packages/db/src/query/live/collection-config-builder.ts
packages/db/tests/query/live-query-collection.test.ts
packages/react-db/tests/useLiveQuery.test.tsx

We were not fully clearing the state of the subscriptions when a live query was cleaned up, this resulted in it trying to resubscribe to its source collection without the initial state.
Failed test run showing the repro before fixing: https://github.com/TanStack/db/actions/runs/17427389243/job/49477526316?pr=484

fix stuck empty remounted live query that uses joins bug

---

.changeset/poor-vans-design.md
packages/react-db/src/useLiveQuery.ts

There is a race condition where data may be loaded into a collection before the `subscribeChanges(() => {})` is called, so `useLiveQuery` does not emit the initial data. This change checks if the collection is ready and will immediately call `onStoreChanges()`, so that the initial data is rendered.
Example:
```ts
export const vehicleDocumentCollection = createCollection({
getKey: (item) => item.id,
schema: vehicleDocumentSchema,
sync: {
sync: async ({ begin, commit, write, markReady }) => {
begin()
for (const doc of docResponse.documents) {
write({ type: 'insert', value: doc })
}
// Initial data is not displayed, `isLoading` is stuck at true, `isReady` is stuck at false 
await new Promise((resolve) => setTimeout(resolve, 0))
// Initial data is displayed, `isLoading: false, isReady: true` …
```

Fix race condition where initial data does not trigger live query

---

.changeset/tame-times-create.md
packages/db-ivm/package.json
packages/db-ivm/src/hashIndex.ts
packages/db-ivm/src/hashing/hash.ts
packages/db-ivm/src/hashing/index.ts
packages/db-ivm/src/hashing/murmur.ts
packages/db-ivm/src/multiset.ts
packages/db-ivm/src/operators/distinct.ts
packages/db-ivm/src/utils.ts
packages/db-ivm/src/valueIndex.ts
packages/db-ivm/tests/utils.test.ts
pnpm-lock.yaml

This PR changes how we hash values. We used to `JSON.stringify` the values and then hash them. Now, we walk over the value's structure and hash each part. This implementation adapts the implementation from the [composites polyfill](https://github.com/tc39/proposal-composites). The composites hashing only supports hashing composites, we adapted it too also handle arrays, maps, and sets. We also support `Buffer`, `Uint8Array`, and `File` but hash them based on their object reference rather than their value because their value is likely to be big and hence hashing it would be too costly.

Replace JSON.stringify based hashing by structural hashing

---

.changeset/wild-seals-smell.md
packages/db/src/query/live/collection-config-builder.ts
packages/db/tests/query/live-query-collection.test.ts

Fixes #320 and replaces #520
thanks to @asabil

fix: use collection key instead of source key when checking for updates in live query collections

---

.changeset/red-sloths-jog.md
packages/db-ivm/src/hashing/hash.ts

fix: Check typeof Buffer before instanceof to avoid ReferenceError in browsers

---

.changeset/brown-trees-pay.md
packages/electric-db-collection/src/electric.ts

Hi! I debugged what was happening in #418 and finally I discovered the issue's cause.
The `AbortController` inside the sync config of `electric-db-collection` after being aborted (by the cleanup fn after the `gcTime` and 0 active subscribers) was never re-initialized again.
And cause the signal was already `aborted`, the electric client skips the sync request! (https://github.com/electric-sql/electric/blob/3baf67a11887fea0bd046b06e081a93f16c88173/packages/typescript-client/src/client.ts#L474)
I only moved the AbortController instantiation inside the sync() function instead of the parent scope.

fix AbortController re-initialization (electric-db-collection)

---

.changeset/heavy-parts-grow.md
packages/db/src/collection-events.ts
packages/db/src/collection.ts
packages/db/tests/collection-events.test.ts

This adds a new event system for generic collection events, such as status changes or notification of the change in subscribers. It's strongly typed based on the passed in event name.
This can be used by #462 as the events to trigger subscribing/unsubscribing from Query. I also intend to use it in a refactor of the live query collection and its status triggers.
We should look to replace `.onFirstReady` with `.once('status:ready', () => ...)` in a followup, and deprecate that api.

New collection event system

---

packages/electric-db-collection/package.json
pnpm-lock.yaml

We have @electric-sql/client as a dependency and you don't want both.

Remove peerDependencies from electric-db-collection

---

.changeset/curvy-mangos-yell.md
packages/db/src/query/optimizer.ts
packages/db/tests/query/join.test.ts

Fixes #574
CI run where the new test failed before the fix: https://github.com/TanStack/db/actions/runs/18094012999/job/51480945391?pr=600

Don't push down where clauses that only touch the namespace of a source and not a prop

---

.changeset/polite-eels-laugh.md
packages/db/src/collection/lifecycle.ts
packages/db/src/collection/state.ts
packages/electric-db-collection/tests/electric-live-query.test.ts

This fixes #597
We were emitting an empty change event whenever `markReady` was called, which would happed after each Electric long polling request returned.
The code that triggers these additional empty events was added in #532 to fix a suck loading state. That PR introduced a test case that failed without this previous change. My change here initially caused a regression, but I went digging and found the *real* case of the stuck loading state and have fixed that 🥳

fix repeated renders when markReady called when collection already ready

---

.changeset/light-moles-divide.md
packages/query-db-collection/src/query.ts
packages/query-db-collection/tests/query.test.ts

Fixes #633 - a regression introduced in #462
Summary of fix from Claude:
The PR aimed to fix `staleTime` behavior by:
1. **Not subscribing** to TanStack Query when `startSync=false` AND `subscriberCount=0`
2. **Dynamically subscribing/unsubscribing** based on subscriber count changes
3. Allowing the QueryObserver to go inactive, restoring proper `staleTime`/`gcTime` semantics
The buggy code checked the subscription condition **inside** the sync function:
```typescript
// Inside the sync function (WRONG LOCATION)
if (config.startSync || collection.subscriberCount > 0) {
subscribeToQuery()
}
```
**Problem**: When `preload()` is called, it starts sync but has:
- `config.startSync` = `undefined`/`false` 
- `collection.subscriberCount` = `0`
- Result: Never subscribes → `queryFn` never runs → …

fix query collection `.preload()`

---

.changeset/good-papers-knock.md
packages/db/src/query/compiler/group-by.ts
packages/db/src/query/compiler/order-by.ts
packages/db/tests/query/order-by.test.ts

fixes #610
Description of the fix from Claude:
When a collection alias in the `from` clause had the same name as one of its schema fields, `orderBy` would fail to sort correctly. For example:
```typescript
type EmailSchema = {
email: string
createdAt: Date
}
// This would break - alias "email" conflicts with the "email" field
q.from({ email: emailCollection })
.orderBy(({ email }) => email.createdAt, "desc")
```
The query would run but produce unsorted results.
The `orderBy` compiler was constructing an evaluation context by spreading the row data and then `__select_results`:
```typescript
const orderByContext = { ...row }
if (row.__select_results) {
Object.assign(orderByContext, row.__select_results)
}
```
When `__select_results` contained a field with the same name as a table alias …

fix orderBy field alias bug

---

.changeset/floppy-wings-mix.md
packages/db/src/collection/index.ts
packages/db/src/collection/subscription.ts
packages/db/src/collection/sync.ts
packages/db/src/index.ts
packages/db/src/query/compiler/expressions.ts
packages/db/src/query/compiler/order-by.ts
packages/db/src/query/live/collection-subscriber.ts
packages/db/src/types.ts
packages/db/tests/query/order-by.test.ts
packages/db/tests/transactions.test.ts
packages/db/tests/utility-exposure.test.ts
packages/react-db/vite.config.ts
pnpm-lock.yaml

This PR modifies tanstack DB to push down predicates to the sync layer.

Predicate pushdown to sync
